# Generated by Django 6.0.2 on 2026-03-01 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_initial'),
        ('trading', '0003_remove_stock_name_stock_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('user', 'stock')},
        ),
    ]
