# Generated by Django 6.0.2 on 2026-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_holding_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
