# Generated by Django 6.0.3 on 2026-03-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lesson_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image_url',
        ),
    ]
