# Generated by Django 6.0.3 on 2026-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='reward_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
