# Generated by Django 5.2.11 on 2026-03-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='order',
            field=models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='log', to='trading.order'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='trading.stock')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['stock', '-recorded_at'], name='trading_pri_stock_i_806a90_idx')],
            },
        ),
    ]
