# Generated by Django 5.2.11 on 2026-03-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_tradelog_order_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.order')),
            ],
        ),
    ]
