# Generated by Django 6.0.2 on 2026-03-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_dailystockprice'),
        ('trading', '0005_alter_order_idempotency_key'),
    ]

    operations = [
    ]
