# Generated by Django 6.0.3 on 2026-03-19 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_limitorder_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='change_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
