# Generated by Django 6.0.3 on 2026-03-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_portfoliosnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioSnapshot',
        ),
    ]
