# Generated by Django 6.0.3 on 2026-03-05 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_profile', models.CharField(max_length=32)),
                ('trade_count_last_7_days', models.IntegerField(default=0)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('portfolio_concentration', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
