# Generated by Django 6.0.3 on 2026-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsight',
            name='portfolio_concentration',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='tips',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='trade_count_last_7_days',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='anomaly_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='summary',
            field=models.TextField(default='initial ai insights'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='trader_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='risk_profile',
            field=models.CharField(choices=[('Conservative', 'Conservative'), ('Balanced', 'Balanced'), ('Aggressive', 'Aggressive')], max_length=20),
        ),
    ]
