# Generated by Django 6.0.3 on 2026-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_remove_aiinsight_portfolio_concentration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='risk_profile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
