# Generated by Django 6.0.3 on 2026-03-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_aiinsight_risk_profile_alter_aiinsight_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsight',
            name='anomaly_detected',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='anomaly_score',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='risk_profile',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='trader_type',
        ),
    ]
